version: '3.8'

services:
  average-calculator:
    build: .
    container_name: average-calculator-microservice
    ports:
      - "9876:9876"
    environment:
      - NODE_ENV=production
      - PORT=9876
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "const http = require('http'); const req = http.request({hostname: 'localhost', port: 9876, path: '/health', timeout: 2000}, (res) => { if (res.statusCode === 200) { process.exit(0); } else { process.exit(1); } }); req.on('error', () => { process.exit(1); }); req.end();"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge